@startuml
left to right direction
actor "Store A" as StoreA
actor "Store B" as StoreB

rectangle "Inventory System" {
  usecase (Item Request & Transfer)
}

(Request Item) --> (Item Request & Transfer)
(Transfer Item) --> (Item Request & Transfer)

StoreA --> (Transfer Item)
StoreB --> (Request Item)

note top of (Item Request & Transfer)
The stock of Item A in Store A decreases
the stock of Item A in Store B increases.
end note

@enduml
