@startuml
left to right direction
actor "Store A" as StoreA
actor "Store B" as StoreB

rectangle "Inventory System" {
  usecase (Item Request & Transfer)
}

(1. Request Item) --> (Item Request & Transfer)
(Item Request & Transfer)

StoreB --> (1. Request Item)
(Item Request & Transfer) --> (2. Confirm Item Request)
(2. Confirm Item Request) --> StoreA
StoreA --> (3. Transfer Item)
(3. Transfer Item) --> (Item Request & Transfer)
(Item Request & Transfer) --> (4. Receipt Item)
(4. Receipt Item) --> StoreB

note top of (Item Request & Transfer)
  The stock of Item A in Store A decreases,
  the stock of Item A in Store B increases.
end note

@enduml
